aspa/aspa/urls.py
from django.contrib import admin
from django.urls import path, include
from frontstore import urls as frontstoreUrls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('frontstore/', include(frontstoreUrls)),
]

aspa/frontstore/urls.py
from django.urls import path
from . import views
from .views import LoginView, LogoutView


urlpatterns = [
    path('create/', views.create_store, name='create_store'),
    path('ajax/load-categories/', views.load_categories, name='ajax_load_categories'),  # AJAX URL
    path('login', LoginView.as_view(), name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout', LogoutView.as_view(), name='logout'),
    # Add additional paths as needed
]

aspa/frontstore/models.py
from django.db import models

# Create your models here.
from django.conf import settings
from aspamain.models import Industry, Category  # Import models from aspamain

class Store(models.Model):
    name = models.CharField(max_length=191)
    description = models.TextField()
    logo = models.ImageField(upload_to='store_logos/', null=True, blank=True)
    website = models.URLField(max_length=200, null=True, blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='stores')
    industry = models.ForeignKey(Industry, on_delete=models.SET_NULL, null=True, related_name='stores')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='stores')
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

aspa/frontstore/forms.py
from django import forms
from .models import Store
from aspamain.models import Industry, Category

class StoreForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = ['name', 'industry', 'category', 'description', 'logo', 'website']
        widgets = {            
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Business Registration Name'}),
            'industry': forms.Select(attrs={'class': 'form-control industry-select'}),
            'category': forms.Select(attrs={'class': 'form-control'}),            
            'description': forms.Textarea(attrs={'class': 'form-control','rows': 3}),
            'logo': forms.FileInput(attrs={'class': 'form-control'}),
            'website': forms.URLInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.none()  # Initially empty

        if 'industry' in self.data:
            try:
                industry_id = int(self.data.get('industry'))
                self.fields['category'].queryset = Category.objects.filter(industry_id=industry_id).order_by('name')
            except (ValueError, TypeError):
                pass  # Invalid input; ignore and default to empty queryset
        elif self.instance.pk:
            self.fields['category'].queryset = self.instance.industry.category_set.order_by('name')

aspa/frontstore/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import View
from django.contrib import messages
from django.http import JsonResponse
from aspamain.models import Category

from .forms import StoreForm

# @method_decorator(login_required, name='dispatch')
def load_categories(request):
    industry_id = request.GET.get('industry_id')
    categories = Category.objects.filter(industry_id=industry_id).order_by('name')
    return JsonResponse(list(categories.values('id', 'name')), safe=False)


@login_required
def create_store(request):
    if request.method == 'POST':
        form = StoreForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            store = form.save(commit=False)
            store.owner = request.user
            store.save()
            return redirect('store_list')  # Redirect to a page listing stores or a confirmation page
    else:
        form = StoreForm(user=request.user)
    
    return render(request, 'frontstore/create_store.html', {'form': form})
# Create your views here.
@login_required
def dashboard(request):

    if request.user.is_authenticated:
        # assets = Asset.objects.filter(createdby_id = request.user.id)
        # assettypes = AssetType.objects.filter(createdby_id = request.user.id)
        # assets = Asset.objects.filter(createdby_id = request.user.id)
        return render(request, 'frontstore/dashboard.html')
    else:
        return redirect('login')


class LoginView(View):
    template_name = 'frontstore/login.html'

    def get(self, request):
        return render(request, self.template_name)
    
    def post(self, request):

    # if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            # A backend authenticated the credentials
            messages.success(request, f'welcome, {user.username}')
            return redirect('dashboard')
        else:
            # No backend authenticated the credentials
             messages.warning(request, 'Invalid login credentials!')
             return render(request, self.template_name)
         
         
class LogoutView(View):
    def get(self, request):
        logout(request)
        messages.info(request, 'Log out successful.')
        return redirect('login')

aspa/frontstore/templates/frontstore/create_store.html
{% extends "base_auth.html" %}
{% block content %}
{% load static %}
        <!-- Login box.scss -->
        <!-- ============================================================== -->
        <div class="auth-wrapper d-flex no-block justify-content-center align-items-center" style="background:url('{% static 'assets/images/big/auth-bg.jpg' %}') no-repeat center center;">
              <div class="auth-box">
                <h5 class="font-medium m-b-20">Create Your Store</h5><br/>
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} border-0 alert-dismissible fade show" role="alert">
                         {{ message }}
                         <button type="button" class="btn-close btn-close-primary" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Create Store</button>
                      </form>
                </div>
        </div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script type="text/javascript">
    $(document).ready(function() {
        $(".industry-select").change(function() {
            var industryId = $(this).val();
            $.ajax({
                url: "{% url 'ajax_load_categories' %}",
                data: {
                    'industry_id': industryId
                },
                success: function(data) {
                    var $categorySelect = $("#id_category");
                    $categorySelect.empty();
                    $categorySelect.append('<option value="">Select a category...</option>');
                    $.each(data, function(key, value) {
                        $categorySelect.append('<option value="' + value.id + '">' + value.name + '</option>');
                    });
                }
            });
        });
    });
  </script>
{% endblock %}

aspa/frontstore/templates/frontstore/dashboard.html
{% extends "base.html" %}
{% block content %}
{% load static %}

    <div class="chat-windows"></div>

{% endblock %}

aspa/frontstore/templates/frontstore/login.html
{% extends "base_auth.html" %}
{% block content %}
{% load static %}
        <!-- Login box.scss -->
        <!-- ============================================================== -->
        <div class="auth-wrapper d-flex no-block justify-content-center align-items-center" style="background:url('{% static 'assets/images/big/auth-bg.jpg' %}') no-repeat center center;">
  
            <div class="auth-box">
                <div id="loginform">
                    <div class="logo">
                        <span class="db"><img src="{% static 'assets/images/logo-icon.png' %}" alt="logo" style="width:100px!important; width:100px!important"/></span>
                        <h5 class="font-medium m-b-20">Sign In to Your Store</h5><br/>
                        {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} border-0 alert-dismissible fade show" role="alert">
                                 {{ message }}
                                 <button type="button" class="btn-close btn-close-primary" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <form class="form-horizontal m-t-20" method="POST" id="loginform" action="">
                                {% csrf_token %}
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1"><i class="ti-user"></i></span>
                                    </div>
                                    <input type="text" name="username" id="username" class="form-control form-control-lg" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
                                </div>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon2"><i class="ti-pencil"></i></span>
                                    </div>
                                    <input type="password" name="password" id="password" class="form-control form-control-lg" placeholder="Password" aria-label="Password" aria-describedby="basic-addon1">
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="customCheck1">
                                            <label class="custom-control-label" for="customCheck1">Remember me</label>
                                            <a href="javascript:void(0)" id="to-recover" class="text-dark float-right"><i class="fa fa-lock m-r-5"></i> Forgot pwd?</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group text-center">
                                    <div class="col-xs-12 p-b-20">
                                        <button class="btn btn-block btn-lg btn-info" type="submit" style="background:#0D59A6!important">Log In</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div id="recoverform">
                    <div class="logo">
                        <span class="db"><img src="{% static 'assets/images/logo-icon.png'%}" alt="logo" /></span>
                        <h5 class="font-medium m-b-20">Recover Password</h5>
                        <span>Enter your Email and instructions will be sent to you!</span>
                    </div>
                    <div class="row m-t-20">
                        <form class="col-12" action="#" id="resetform">                          
                             <div class="form-group row">
                                <div class="col-12">
                                    <input class="form-control form-control-lg" type="email" required="" placeholder="Username">
                                </div>
                            </div>
                            <div class="row m-t-20">
                                <div class="col-12">
                                    <button class="btn btn-block btn-lg btn-danger" type="submit" name="action">Reset</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}